name: baselines
dependencies:
    - python==3.5.2
    - numpy
    - scipy
    - path.py
    - python-dateutil
    - mako
    - ipywidgets
    - numba
    - flask
    - h5py
    - matplotlib
    - scikit-learn
    - mpi4py
    - pandas
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - tqdm
        - msgpack-python
        - cached_property
        - line_profiler
        - cloudpickle
        - Cython
        - redis
        - awscli
        - mujoco-py==0.5.7
        - gym==0.7.4
        - pyglet
        - jupyter
        - progressbar2
        - tensorflow-gpu==1.12.0
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
        - hyperopt
        - polling
        - gtimer
        - visdom
        - opencv-python
        - dill
        - joblib
        - zmq
        - click
